server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://ms-user
          predicates:
            - Path=/api/users/**, /api/auth/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /$\{segment}
            - RewritePath=/api/auth/(?<segment>.*), /api/auth/$\{segment}
