server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Route pour MS-User
        - id: user-service
          uri: lb://ms-user
          predicates:
            - Path=/api/users/**, /api/auth/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /$\{segment}
            - RewritePath=/api/auth/(?<segment>.*), /api/auth/$\{segment}
        
        # Route pour MS-Patients
        - id: patient-service
          uri: lb://ms-patients
          predicates:
            - Path=/api/patients/**
        
        # Route pour MS-Notes
        - id: notes-service
          uri: lb://ms-notes
          predicates:
            - Path=/api/notes/**
        
        # Route pour MS-Assessment
        - id: assessment-service
          uri: lb://ms-assessment
          predicates:
            - Path=/api/assessments/**
            
        # Route pour MS-WebApp (modifié)
        - id: webapp-service
          uri: lb://ms-webapp # URL directe au lieu de lb://ms-webapp
          predicates:
            - Path=/api/webapp/**
      
      # Configuration CORS globale
# Configuration CORS globale
        globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins: "http://localhost:5173"  # Remplacez * par l'URL spécifique
              allowedMethods: "GET,POST,PUT,DELETE,OPTIONS"
              allowedHeaders: "Authorization,Content-Type"
              allowCredentials: true
              maxAge: 3600
# Configuration Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance:
    preferIpAddress: false  # Changé pour être cohérent
    hostname: localhost     # Ajouté pour spécifier l'hôte
# Configuration de monitoring
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,gateway"
  endpoint:
    health:
      show-details: ALWAYS
# Configuration de résilience
resilience4j:
  circuitbreaker:
    instances:
      defaultCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
  timelimiter:
    instances:
      defaultTL:
        timeoutDuration: 5s
