server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Route pour MS-User
        - id: user-service
          uri: lb://ms-user
          predicates:
            - Path=/api/users/**, /api/auth/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /${segment}
            - RewritePath=/api/auth/(?<segment>.*), /api/auth/${segment}
            
        # Route pour MS-Patients (sans réécriture de chemin)
        - id: patient-service
          uri: lb://ms-patients
          predicates:
            - Path=/api/patients/**
            
        # Route pour MS-Notes
        - id: notes-service
          uri: lb://ms-notes
          predicates:
            - Path=/api/notes/**
            
        # Route pour MS-Assessment (Nouvelle route ajoutée)
        - id: assessment-service
          uri: lb://ms-assessment
          predicates:
            - Path=/api/assessments/**
            - Path=/graphql
      
      # Configuration CORS globale
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            maxAge: 3600
# Configuration Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance:
    preferIpAddress: true
# Configuration de monitoring
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
