spring:
  cloud:
    gateway:
      routes:
        # Routes existantes
        - id: user-service
          uri: lb://ms-user
          predicates:
            - Path=/api/users/**, /api/auth/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /$\{segment}
            - RewritePath=/api/auth/(?<segment>.*), /api/auth/$\{segment}
            
        # Nouvelle route pour MS-Patient
        - id: patient-service
          uri: lb://ms-patient
          predicates:
            - Path=/api/patients/**
          filters:
            - RewritePath=/api/patients/(?<segment>.*), /patients/$\{segment}
