spring:
  cloud:
    gateway:
      routes:
        # Routes existantes
        - id: user-service
          uri: lb://ms-user
          predicates:
            - Path=/api/users/**, /api/auth/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /$\{segment}
            - RewritePath=/api/auth/(?<segment>.*), /api/auth/$\{segment}
            
        # Route corrigée pour MS-Patients (pluriel)
        - id: patient-service
          uri: lb://ms-patients
          predicates:
            - Path=/api/patients/**
          filters:
            - RewritePath=/api/patients(?<segment>.*), /patients$\{segment}
