spring:
  application:
    name: ms-assessment
  config:
    import: "optional:configserver:http://localhost:9000"
  datasource:
    url: jdbc:mysql://localhost:3306/healthcare_assessment?createDatabaseIfNotExist=true
    username: root
    password: motdepasse123*
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance:
    preferIpAddress: true

feign:
  circuitbreaker:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
