server:
  port: 8084

spring:
  application:
    name: ms-assessment
  datasource:
    url: jdbc:mysql://localhost:3306/healthcare_assessment?createDatabaseIfNotExist=true
    username: root
    password: motdepasse123*
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance:
    preferIpAddress: true

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: ERROR
    net.healthcare: DEBUG
