server:
  port: 8084
  servlet:
    context-path: /

# Spring Configuration
spring:
  # Application Name
  application:
    name: ms-assessment

  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/healthcare_assessment?createDatabaseIfNotExist=true
    username: root
    password: motdepasse123*
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  # GraphQL Configuration
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    schema:
      locations: classpath:graphql/**
      printer:
        enabled: true

  # Logging Configuration
  logging:
    level:
      org.springframework.web: INFO
      org.hibernate: ERROR
      net.healthcare: DEBUG

# Eureka Service Discovery Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance:
    preferIpAddress: true
