server:
  port: 8082
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/healthcare_patients?createDatabaseIfNotExist=true
    username: root
    password: motdepasse123*
  jpa:
    hibernate:
       ddl-auto: create-drop
    show-sql: true

healthcare:
  app:
    jwtSecret: yourVerySecureJwtSecretKeyShouldBeLongAndHardToGuess
    jwtExpirationMs: 86400000  # 24 heures

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

