server:
  port: 8086
  servlet:
    context-path: /api/webapp  # Le context-path est modifié pour être cohérent
spring:
  application:
    name: ms-webapp  # Assurez-vous que le nom est correct pour Eureka
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081
# Configuration JWT
healthcare:
  app:
    jwtSecret: yourVerySecureJwtSecretKeyShouldBeLongAndHardToGuess
    jwtExpirationMs: 86400000  # 24 heures
# Configuration Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true  # Modifié à false pour utiliser hostname plutôt que l'IP
   # hostname: ms-webapp    # Ajouté pour spécifier explicitement l'hôte
   # instanceId: ${spring.application.name}:${server.port}  # ID d'instance unique
# Le reste de la configuration reste identique
# Configuration Feign
feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
# Configuration de monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: ALWAYS
  health:
    circuitbreakers:
      enabled: true
# Configuration de résilience
resilience4j:
  circuitbreaker:
    instances:
      userService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
      patientService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
      notesService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
      assessmentService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
# URLs des microservices
service:
  user:
    url: lb://ms-user
  patient:
    url: lb://ms-patients
  notes:
    url: lb://ms-notes
  assessment:
    url: lb://ms-assessment
# Configuration de logging
logging:
  level:
    net.webapp: DEBUG  # Modifié pour correspondre au package réel
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.cloud.openfeign: DEBUG
